//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resx2Xls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resx2Xls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * If the text contains a line break, please add a line break at the same point in the text, using the keyboard shortcut Alt + Enter.
        /// </summary>
        internal static string explanation_excel_newline {
            get {
                return ResourceManager.GetString("explanation_excel_newline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Check if the translations in the green cells are still correct; if not, please translate them again.
        /// </summary>
        internal static string explanation_green {
            get {
                return ResourceManager.GetString("explanation_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Excel file contains all you need to create a new translation. Please use the file as follows:.
        /// </summary>
        internal static string explanation_header {
            get {
                return ResourceManager.GetString("explanation_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The screenshots serve as examples; from these screenshots, you can make an estimation of how much space is available for pieces of texts.
        /// </summary>
        internal static string explanation_screenshot1 {
            get {
                return ResourceManager.GetString("explanation_screenshot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Do not translate any texts because they are on the screenshots; only translate those texts that are in the cells of the excel sheet.
        /// </summary>
        internal static string explanation_screenshot2 {
            get {
                return ResourceManager.GetString("explanation_screenshot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * If the text contains codes like {0}, please keep them in the translated text in the same location (numbers are inserted into the texts at these points).
        /// </summary>
        internal static string explanation_string_inserts {
            get {
                return ResourceManager.GetString("explanation_string_inserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please translate all the yellow cells.
        /// </summary>
        internal static string explanation_yellow {
            get {
                return ResourceManager.GetString("explanation_yellow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap finishbar {
            get {
                object obj = ResourceManager.GetObject("finishbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leftbar {
            get {
                object obj = ResourceManager.GetObject("leftbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing excel file...
        /// </summary>
        internal static string parsing_excel {
            get {
                return ResourceManager.GetString("parsing_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing resx files...
        /// </summary>
        internal static string parsing_resx {
            get {
                return ResourceManager.GetString("parsing_resx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:
        ///Build an Excel document from your default language resource..
        /// </summary>
        internal static string summary_create_excel {
            get {
                return ResourceManager.GetString("summary_create_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation:
        ///Build your localized resource files from an Excel document..
        /// </summary>
        internal static string summary_create_resx {
            get {
                return ResourceManager.GetString("summary_create_resx", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap topbar {
            get {
                object obj = ResourceManager.GetObject("topbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
